### ISSUE TITLE
AssertjAssertThatThrownBy produces code that doesn't compile in some cases

### ISSUE THREAD

**Issue by carterkozak** [palantir/assertj-automation#79]
## What happened?
AssertjAssertThatThrownBy migrates code to a lambda, which requires all referenced fields to be final or effectively final.

## What did you want to happen?

It would be helpful if we could fail the check without suggesting a fix in these cases in order to allow strict projects to use final values while avoiding creating PRs with code that doesn't compile for projects with limited maintenance.

I think we can leverage something along these lines to detect cases that cannot be converted to lambdas: https://github.com/google/error-prone/commit/0a6a37fc8360835389d276ae57543a57dc9d4917

**Comment by carterkozak** [comment]
@fawind Interested in taking a look at this when you have a moment?

**Comment by fawind** [comment]
Sure! The `ASTHelpers` look promising. Will have a look on Monday.

**Comment by carterkozak** [comment]
fixed by #126
